# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://wmcee2025.github.io
title: Wikimedia CEE Meeting 2025
email: riggas@ionio.gr
author: Dimitrios Ringas
description: > # "Write an awesome description for your new site here. 
  Wikimedia CEE Meeting 2025 (#WMCEE) is an annual conference centered on Wikimedia projects (Wikipedia and other related projects) 
  in countries of Central and Eastern Europe (more recently, also in Central Asia). It features presentations on Wikimedia projects, 
  other wikis, free/open source software, free knowledge and free content, and the social and technical aspects of these topics. 
  The 2025 meeting will be held in Thessaloniki, Greece, 26-28 September, organized by Wikimedia UG Greece. 
copyright: '2025 Wikimedia UG Greece.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Wikimedia Meta page 
    icon: globe
    url: https://meta.wikimedia.org/wiki/Wikimedia_CEE_Meeting_2025
